repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
  - repo: local
    hooks:
    - id: prospector
      name: prospector
      entry: prospector
      language: system
      types: [python]
