doc-warnings: true
test-warnings: true
strictness: veryhigh

pylint:
  run: false
  disable:
    -E0001

pep8:
  run: true
  full: true

pep257:
  run: true
  disable:
    # These ones are ignored because the `missing-docstring` is checked
    # by `pylint` and it has an option called `docstring-min-length`
    # which is set to 20. So, methods that are < 20 lines do not
    # require docstring. In this case, `pep257` will fail because it
    # will say the docstring is required.
    - D203
    - D212
  enable:
    # pydocstyle
    - D401

pyflakes:
  run: false
