doc-warnings: true
test-warnings: true
strictness: veryhigh
member-warnings: false

pylint:
  full: true
  run: true
  disable:
    - E401
    - E501
  options:
    max-line-length: 99

pep8:
  full: true
  run: true
  disable:
    # pycodestyle
    - E203
    - E401
    - E501
  options:
    max-line-length: 99

pep257:
  full: true
  run: true
  disable:
    # These ones are ignored because the `missing-docstring` is checked
    # by `pylint` and it has an option called `docstring-min-length`
    # which is set to 20. So, methods that are < 20 lines do not
    # require docstring. In this case, `pep257` will fail because it
    # will say the docstring is required.
    - D203
    - D212
  enable:
    # pydocstyle
    - D401
  options:
    max-line-length: 99

pyflakes:
  full: true
  run: false
  disable:
    # pycodestyle
    - E401
    - E501
  options:
    max-line-length: 99

pycodestyle:
  full: true
  run: true
  options:
    max-line-length: 99

mccabe:
  run: true

pyroma:
  run: true

mypy:
  run: true
  ignore_missing_imports: true

bandit:
  run: true
