#!/usr/bin/env bash
require() {
hash "$@" || exit 127;
}
require mkdir find parallel cp
mkdir -p "${PREFIX}/home/storage/downloads/Pydocs"
find . -name "*.xlsx" | parallel -I% --max-args 1 cp % "${PREFIX}/home/storage/downloads/Pydocs"
find . -name "*.csv" | parallel -I% --max-args 1 cp % "${PREFIX}/home/storage/downloads/Pydocs"
find . -name "*.docx" | parallel -I% --max-args 1 cp % "${PREFIX}/home/storage/downloads/Pydocs"
find . -name "*.pptx" | parallel -I% --max-args 1 cp % "${PREFIX}/home/storage/downloads/Pydocs"
