#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

script_dir="$(dirname "$(realpath -s "${BASH_SOURCE[0]}")")"
source "${script_dir}/require.sh" || {
  printf "Error: Failed to source required file: %s/require.sh\n" "${script_dir}" >&2
  exit 1
}

require mkdir
require find
require parallel
require cp

if [[ -d "/data/data/com.termux" ]]; then
  # Termux Android
  plots_dir="${HOME}/storage/downloads/Pyplots/"
elif [[ -f "/etc/arch-release" ]]; then
  # Arch Linux
  plots_dir="${HOME}/downloads/Pyplots/"
elif [[ -f "/etc/lsb-release" ]] && grep -q "Ubuntu" /etc/lsb-release; then
  # Ubuntu
  plots_dir="${HOME}/downloads/Pyplots/"
else
  # Default case
  plots_dir="${HOME}/downloads/Pyplots/"
fi

mkdir -p "${plots_dir}"

find . -name "*.pdf" | parallel -I% --max-args 1 cp % "${plots_dir}"
find . -name "*.png" | parallel -I% --max-args 1 cp % "${plots_dir}"
find . -name "*.jpg" | parallel -I% --max-args 1 cp % "${plots_dir}"
