#!/usr/bin/env bash

#######################################################################
#@author: Linus Fernandes(linusfernandes @gmail.com)
# @file: formatandlint
## @created: Wed 25 Sep 2019.
# @copyright: Copyright(c) Linus Fernandes
## @description: 
######################################################################
usage() {
        echo "usage: formatandlint dir"
        echo "dir - Project directory, must exist"
        exit 1
}

proj=$1
declare -i SUCCESS=0
if [ -z "$proj" ] || [ ! -d "$proj" ]
  then
    usage
else
    echo "$proj"
    autopep8 --in-place --aggressive -r "$proj"
   SUCCESS=SUCCESS+$?
   pylint "$proj" -r yes -f colorized | tee linter.out
   SUCCESS=SUCCESS+$?
#    prospector "$proj" | tee -a linter.out
#   SUCCESS=SUCCESS+$?
fi
exit $SUCCESS
