#!/usr/bin/env bash
function require() {
hash "$@" || exit 127;
}
require pip virtualenv tee rm

function egress() {
  echo "deactivating virtualenv..." | tee venv.txt
  deactivate
  echo "Removing directory venv..." | tee -a venv.txt
  rm -rf venv
  echo "Process $$ exiting..."
  exit 1
}
trap egress SIGTERM EXIT
pip install virtualenv
virtualenv venv
# shellcheck disable=SC1091
source venv/bin/activate
pip install flask python-dotenv
./app.py 
