#!/usr/bin/env bash
require() {
hash "$@" || exit 127;
}
require curl jq cat rm pgrep
curl -ILs http://localhost:5000/v1/users/
curl -Ls http://localhost:5000/v1/users/ | jq .
curl -Ls http://localhost:5000/v1/users/1 | jq .
curl -Ls http://localhost:5000/v1/users/2 | jq .
curl -s -X POST 'http://localhost:5000/v1/users/' \
-H 'Content-Type: application/json' -d '{"username": "macintosh","email": "mack@jack.com"}' | jq .
curl -Ls http://localhost:5000/v1/users/3 | jq .
curl -Ls -X PUT 'http://localhost:5000/v1/users/3' \
-H 'Content-Type: application/json' -d '{"username": "jewess","email": "jane@jack.com"}' | jq .
curl -Ls http://localhost:5000/v1/users/3 | jq .
curl -Ls -X DELETE 'http://localhost:5000/v1/users/3' | jq .
curl -Ls http://localhost:5000/v1/users/ | jq .
pgrep 'python'
pid=$(cat app.pid)
echo "Killing app.py... with pid: " "$pid"
kill -SIGTERM "$pid"
echo "Removing app.pid..."
rm app.pid
