#!/usr/bin/env bash
curl -ILs http://localhost:5000/v1/users/
curl -Ls http://localhost:5000/v1/users/ | jq .
curl -Ls http://localhost:5000/v1/users/1 | jq .
curl -Ls http://localhost:5000/v1/users/2 | jq .
curl -X POST "http://localhost:5000/v1/users/" \
-H "Content-Type: application/json" -d '{"username": "macintosh","email": "mack@jack.com"}' -s | jq .
curl -Ls http://localhost:5000/v1/users/3 | jq .
ps aux | grep 'python' | grep -v 'grep'
pid=$(cat app.pid)
echo "Killing app.py... with pid: " "$pid"
kill -9 "$pid"
echo "Removing app.pid..."
rm app.pid
